-- Allergen catalog. INSERT IGNORE keeps re-runs idempotent (code is unique).
-- Animal-derived groups (milk, egg, seafood) are omitted: the platform is fully vegan (BR-06).
INSERT IGNORE INTO allergens (code, name, category) VALUES
('GLUTEN', 'Gluten (lúa mì, lúa mạch)', 'GRAIN'),
('BUCKWHEAT', 'Kiều mạch', 'GRAIN'),
('CORN', 'Bắp (ngô)', 'GRAIN'),
('PEANUT', 'Đậu phộng', 'LEGUME'),
('SOY', 'Đậu nành', 'LEGUME'),
('MUNG_BEAN', 'Đậu xanh', 'LEGUME'),
('CASHEW', 'Hạt điều', 'NUT_SEED'),
('TREE_NUT', 'Hạt cây khác (hạnh nhân, óc chó, mắc ca)', 'NUT_SEED'),
('SESAME', 'Mè (vừng)', 'NUT_SEED'),
('COCONUT', 'Dừa', 'NUT_SEED'),
('TOMATO', 'Cà chua', 'VEGETABLE'),
('EGGPLANT', 'Cà tím', 'VEGETABLE'),
('TARO', 'Khoai môn', 'VEGETABLE'),
('CASSAVA', 'Khoai mì (sắn)', 'VEGETABLE'),
('BAMBOO_SHOOT', 'Măng', 'VEGETABLE'),
('CELERY', 'Cần tây', 'VEGETABLE'),
('CORIANDER', 'Rau mùi (ngò)', 'VEGETABLE'),
('GARLIC', 'Tỏi', 'VEGETABLE'),
('ONION', 'Hành', 'VEGETABLE'),
('MANGO', 'Xoài', 'FRUIT'),
('PINEAPPLE', 'Dứa (thơm)', 'FRUIT'),
('PAPAYA', 'Đu đủ', 'FRUIT'),
('AVOCADO', 'Bơ', 'FRUIT'),
('DURIAN', 'Sầu riêng', 'FRUIT'),
('JACKFRUIT', 'Mít', 'FRUIT'),
('LYCHEE', 'Vải', 'FRUIT'),
('STRAWBERRY', 'Dâu tây', 'FRUIT'),
('MUSHROOM', 'Nấm (các loại)', 'MUSHROOM'),
('CHILI', 'Ớt', 'SPICE'),
('MUSTARD', 'Mù tạt', 'SPICE'),
('SULPHITE', 'Sulfite', 'ADDITIVE'),
('MSG', 'Bột ngọt (MSG)', 'ADDITIVE');
